import { NextRequest, NextResponse } from "next/server";
import JSZip from "jszip";

export async function GET(req: NextRequest) {
  try {
    const data = req.nextUrl.searchParams.get("data");

    if (!data) {
      return NextResponse.json(
        { error: "Missing data query parameter" },
        { status: 400 }
      );
    }

    // Decode the base64url-encoded JSON
    let latex: string;
    let fileName: string;

    try {
      const decoded = Buffer.from(data, "base64url").toString("utf-8");
      const parsed = JSON.parse(decoded);
      latex = parsed.latex;
      fileName = parsed.fileName || "resume";
    } catch {
      return NextResponse.json(
        { error: "Invalid data parameter" },
        { status: 400 }
      );
    }

    if (!latex) {
      return NextResponse.json(
        { error: "No LaTeX content in data" },
        { status: 400 }
      );
    }

    // Create the ZIP file with main.tex
    const zip = new JSZip();
    zip.file("main.tex", latex);
    zip.file(
      "README.txt",
      `Resume: ${fileName}\nGenerated by Resume Architect v26\nOpen main.tex in Overleaf to compile.\n\nTo compile:\n1. This project should auto-compile in Overleaf\n2. If not, click "Recompile" in the top bar\n3. Make sure the compiler is set to pdfLaTeX`
    );

    const zipBuffer = await zip.generateAsync({
      type: "nodebuffer",
      compression: "DEFLATE",
      compressionOptions: { level: 6 },
    });

    return new NextResponse(zipBuffer, {
      status: 200,
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": `attachment; filename="${fileName}.zip"`,
        "Cache-Control": "no-store, max-age=0",
      },
    });
  } catch (err) {
    console.error("Overleaf ZIP route error:", err);
    return NextResponse.json(
      { error: "ZIP generation failed" },
      { status: 500 }
    );
  }
}
