import { NextRequest, NextResponse } from "next/server";
import JSZip from "jszip";

export async function POST(req: NextRequest) {
  try {
    const { latex, fileName } = await req.json();

    if (!latex || !fileName) {
      return NextResponse.json({ error: "latex and fileName required" }, { status: 400 });
    }

    // Create a .zip with main.tex
    const zip = new JSZip();
    zip.file("main.tex", latex);

    // Add a minimal preamble note
    zip.file("README.txt", `Resume: ${fileName}\nGenerated by Resume Architect v26\nOpen main.tex in Overleaf to compile.`);

    const zipBuffer = await zip.generateAsync({ type: "nodebuffer" });

    // Encode to base64 for the "Open in Overleaf" snip URI approach
    // We serve the zip file and construct the Overleaf URL
    const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000";
    const encoded = Buffer.from(JSON.stringify({ latex, fileName })).toString("base64url");
    const zipServeUrl = `${appUrl}/api/overleaf/zip?data=${encoded}`;
    const overleafUrl = `https://www.overleaf.com/docs?snip_uri=${encodeURIComponent(zipServeUrl)}`;

    return NextResponse.json({ success: true, overleafUrl });
  } catch (err) {
    return NextResponse.json({ error: "Overleaf URL generation failed" }, { status: 500 });
  }
}
